-- Generated from the current Command Center API.
-- Safe to rerun: existing rows are replaced with the latest exported values.
DELETE FROM milestones;
DELETE FROM risks;
DELETE FROM timelines;
DELETE FROM tasks;
DELETE FROM project_control_history;
DELETE FROM project_controls;
DELETE FROM projects;
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (1, 'WPR Unit 1', 'WPR', 'Units 1-6', 'Big-D Units 1-6', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (1, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (1, 1, 'Admin: Lvl 2 Family Room - review current proposed short throw projector/screen and BigD provided millwork plan for fit & feedback. BigD is scheduling a meeting to review.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (2, 1, 'Install: INSTALL GIG SWITCH', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (3, 1, 'Install: Unit 1 - Level 2 - observation 2415 - Av not to right dimension, does not line up (THE REQUEST IS THAT IT NEEDS TO BE CENTERED ON THE DOOR) WAP-202', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (4, 1, 'Install: Lvl 1 - AV Mech - missing AV panel cover (see if we can find this onsite somewhere', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (6, 1, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (7, 1, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (8, 1, 'Install: UL pendent speaker', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (210, 1, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (230, 1, 'Procore #3373: Need Form Work Removed for Planter Wall Panels', 'done', 'procore', 'https://app.procore.com/webclients/host/companies/9207/projects/2653585/tools/observations/quality/details/21766667');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (239, 1, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (1, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (1, 'prewire', 'Pre-Wire', '', '', 'complete');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (1, 'trim', 'Trim', '', '', 'complete');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (1, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (2, 'WPR Unit 2', 'WPR', 'Units 1-6', 'Big-D Units 1-6', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (2, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (64, 2, 'Admin: Big-D Information Request - go into system to double check product documentation. Wwhat they are asking for is in the notes. (AV/Security/Shades) if we don''t have an equipment contract it will be prewire as-builts only (mickie can provide a document she created for security)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (65, 2, 'Install: Reminder, Turn on "Auto Reboot" On PDU 1. When the network is up an running.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (66, 2, 'Install: Install GiG Switch', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (67, 2, 'Install: Sonos Will need to be turned over to the customer', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (68, 2, 'Install: Still need the customers WiFi SSID and password', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (69, 2, 'Install: L1 - Garage: Verify wiring location for camera installation', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (70, 2, 'Install: L3 - Flex Room: Trim out TV wiring (shielded Cat6, blue and grey Cat6)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (71, 2, 'Install: L3 - Terrace: Has the camera wiring location been finalized and ready for install?', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (72, 2, 'Install: Lvl2 Bed 5 - tv single gang box height does not match power. (Too high)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (75, 2, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (211, 2, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (2, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (2, 'prewire', 'Pre-Wire', '', '', 'complete');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (2, 'trim', 'Trim', '', '', 'complete');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (2, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (3, 'WPR Unit 3', 'WPR', 'Units 1-6', 'Big-D Units 1-6', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (3, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (76, 3, 'Admin: Unit 3 - Observation #2027: QC - FIELD OBSERVATION - Doorbell Wrong Location', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (77, 3, 'Install: Install GIG Switch', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (78, 3, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (79, 3, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (80, 3, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (81, 3, 'Install: Was primary closet', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (212, 3, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (3, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (3, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (3, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (3, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (4, 'WPR Unit 4', 'WPR', 'Units 1-6', 'Big-D Units 1-6', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (4, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (82, 4, 'Admin: Unit 4 - Lvl 3 - Flex - will need horizontal adapter for tv mount with where the WB was placed on the wall (see pic in notes)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (83, 4, 'Admin: Unit 4 - Primary Bedroom - possibly need vertical adapter for tv mount with where the back box is placed. See pic in notes', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (84, 4, 'Admin: AV Deposit has been paid', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (85, 4, 'Admin: As-builts turned into design 5/20/26', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (86, 4, 'Admin: Update as-built', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (87, 4, 'Install: Install GIG SWITCH', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (88, 4, 'Install: Lvl 3 - we are not doing pendant speakers in this unit. We need to clean up the speaker wire hanging from the beams', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (89, 4, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (90, 4, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (91, 4, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (92, 4, 'Install: Level 1: Garage - Locate camera wiring and expose', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (213, 4, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (4, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (4, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (4, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (4, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (5, 'WPR Unit 5', 'WPR', 'Units 1-6', 'Big-D Units 1-6', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (5, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (93, 5, 'Admin: Unit 5 - Lvl 2 - Family - WB box is not centered, need horizontal adapter for tv mount at install (pic in notes)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (94, 5, 'Install: INSTALL GIG SWITCH', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (95, 5, 'Install: Unit 5 - LVL 2 - bedrooms entry - do we need to center this AP? Talk to Tanner (pic in notes)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (96, 5, 'Install: Lvl 1 - AV Mech - Missing Av Panel Brush Plate (look around onsite to see if you can find this)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (97, 5, 'Install: Tanner''s List 5/18 - General item - Low voltage trim (verify all trim out locations have been terminamted and are ready for wall plates.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (98, 5, 'Install: Tanner''s List 5/18 - Garage - ATI - Clarify what boxes in the ceiling can be covered or patched (mark using tape)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (99, 5, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (100, 5, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (101, 5, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (214, 5, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (5, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (5, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (5, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (5, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (6, 'WPR Unit 6', 'WPR', 'Units 1-6', 'Big-D Units 1-6', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (6, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (102, 6, 'Admin: Review plans 3/16/26 for changes (link in notes) - No green light until we get approval.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (103, 6, 'Install: INSTALL GIG SWITCH', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (104, 6, 'Install: Primary SITTING - install WB21 back box', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (105, 6, 'Install: Lvl 1 front door - stone needs cut for doorbell box', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (106, 6, 'Install: Lvl 3 Flex Room - verify WB26 is installed (65" Tv going here)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (107, 6, 'Install: PENDING APPROVAL - Bedrooms 1,2,3,4 will get WB21 Tv Back Boxes (for 55" Tvs)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (108, 6, 'Install: Lvl 2 Bed 4 - Install WB 21 (Pending Bedroom Back Box Proposal)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (109, 6, 'Install: Lvl 2 Bed 3 - Install WB 21 (Pending Bedroom Back Box Proposal)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (110, 6, 'Install: Lv2 Primary Bedroom - Install WB 21 (Pending Bedroom Back Box Proposal)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (111, 6, 'Install: Lvl 1 Bed 2 - Install WB 21 (Pending Bedroom Back Box Proposal)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (112, 6, 'Install: Lvl 1 Bed 1 - Install WB 21 (Pending Bedroom Back Box Proposal)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (113, 6, 'Install: Lvl 1 AV Mech Room - Panel Clean up - Terminations upon contract', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (114, 6, 'Install: Lvl 1 AV Mech Room - Fiber junction box solution with Big-D', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (115, 6, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (116, 6, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (117, 6, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (215, 6, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (6, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (6, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (6, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (6, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (7, 'WPR Unit 7', 'WPR', 'Units 7-12', 'Big-D Units 7-12', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (7, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (118, 7, 'Admin: Item needs to be added/requested in WeQuote for the job: (1ea) Future Automation IWRE4. Note taken by Quincy on 1/21/26', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (119, 7, 'Admin: All bedrooms will be getting WB boxes. Need sizes and approval', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (120, 7, 'Admin: Lvl 3 - Living - verify with Landon we are blind wiring the tv location or putting up single gang box', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (121, 7, 'Admin: Eliminate all security wiring? Bury? what are we doing with the panel? (I will discuss on 2/20 from Landon)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (122, 7, 'Admin: Lvl 3 Flex Room - will need horizontal adapter for mounting TV at install', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (123, 7, 'Install: PENDING APPROVAL - Bedroom 1,2,3,4 will get WB26 Tv back boxes (for 65" Tvs)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (124, 7, 'Install: Lvl 3 WestTerrace - Land speaker wire (2) in planter boxes once the planter boxes have been installed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (125, 7, 'Install: Lvl 2 Bed 4 - Install WB 26 (Pending Bedroom Back Box Proposal)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (126, 7, 'Install: Lvl 2 Bed 3 - (Pending Bedroom Back Box Proposal) we don’t have enough depth for the WB26, we only have 2.25” of depth. Need a solution for this. (See note for picture)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (127, 7, 'Install: Lvl 1 Bed 2 - Install WB 26 (Pending Bedroom Back Box Proposal)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (128, 7, 'Install: Lvl 1 Bed 1 - Install WB 26 (Pending Bedroom Back Box Proposal)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (129, 7, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (130, 7, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (131, 7, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (132, 7, 'Install: Walk unit and mark up plan accordingly. Install cover plates where needed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (216, 7, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (240, 7, 'Install: LVL3: Patio - Verify WAP wiring', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (241, 7, 'Install: LVL3: Kitchen - Line up WAP wiring with sprinkler head', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (242, 7, 'Install: LVL1: Mudroom - Move WAP wires in line with lights', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (7, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (7, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (7, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (7, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (8, 'WPR Unit 8', 'WPR', 'Units 7-12', 'Big-D Units 7-12', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (8, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (133, 8, 'Admin: Item needs to be added/requested in WeQuote for the job: (1ea) Future Automation IWRE4. Note taken by Quincy on 1/21/26', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (134, 8, 'Admin: Unit 8 level 1 bed 1 wap', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (135, 8, 'Admin: Unit 8 access control', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (136, 8, 'Admin: Unit 8 - update WB back box locations and list (possible changes)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (137, 8, 'Install: Lvl 3 WestTerrace - Land speaker wire (2) in planter boxes once the planter boxes have been installed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (138, 8, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (139, 8, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (140, 8, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (217, 8, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (243, 8, 'Install: LVL3: Kitchen - Line up WAO wiring with sprinkler head', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (8, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (8, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (8, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (8, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (9, 'WPR Unit 9', 'WPR', 'Units 7-12', 'Big-D Units 7-12', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (9, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (147, 9, 'Install: WB Back boxes are onsite (9 total) - these need to be installed. Some areas still need framing finished. (talk to Bill about which areas still need framing completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (148, 9, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (149, 9, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (150, 9, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (219, 9, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (9, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (9, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (9, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (9, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (10, 'WPR Unit 10', 'WPR', 'Units 7-12', 'Big-D Units 7-12', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (10, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (141, 10, 'Install: NEED FRAMING COMPLETED for WB Back boxes (8 total) - talk to Bill to make sure they have the info and layouts needed to complete framing.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (142, 10, 'Install: Place staging request with warehouse for WB Back Boxes once framing is complete.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (143, 10, 'Install: Install WB Back boxes (8 total)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (144, 10, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (145, 10, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (146, 10, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (218, 10, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (10, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (10, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (10, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (10, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (11, 'WPR Unit 11', 'WPR', 'Units 7-12', 'Big-D Units 7-12', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (11, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (151, 11, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (152, 11, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (153, 11, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (220, 11, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (11, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (11, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (11, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (11, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (12, 'WPR Unit 12', 'WPR', 'Units 7-12', 'Big-D Units 7-12', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (12, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (221, 12, 'Install: Splice speaker wiring in rooftop junction boxes', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (244, 12, 'Install: Level 2: Family Room - right rear speaker wire needs brought down off of I-beam', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (12, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (12, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (12, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (12, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (13, 'WPR Condo 101', 'WPR', 'Condos/Penthouse', 'Big-D Condos/Penthouse', 0, '2025-06-02', '2026-09-01');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (13, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (22, 13, 'Admin: How can we integrate with HVAC system?', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (23, 13, 'Admin: What is the overall WAP count?', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (24, 13, 'Admin: Primary Closet - need a change order to swap the 2 current speakers to a DVC due to speaker placement capability', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (25, 13, 'Admin: Update As-builts - Primary Closet change from 2 speakers to 1 DVC (once the work has been completed)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (26, 13, 'Admin: Correct the Lighting Plan based on Thomas Hickman''s markup.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (27, 13, 'Install: Unit 101 Bed 3 TV Back Box Not Level', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (28, 13, 'Install: AV Mech Room - PICTURES OF SERVICE SMURF TUBE PRE-DRYWALL (USE DURING INSTALL)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (29, 13, 'Install: RTV Locations - Crestron D30 (Sh.Cat6 IP Video) / PDU (network) / Tv (network & IR)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (30, 13, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (31, 13, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (32, 13, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (33, 13, 'Install: Turn auto reboot back on in rack PDU 1 once rack is up and running stable.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (247, 13, 'Warehouse: Please stage the bin for this job', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (13, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (13, 'prewire', 'Pre-Wire', '', '', 'complete');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (13, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (13, 'install', 'Install', '2026-08-10', '2026-08-24', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (14, 'WPR Condo 102', 'WPR', 'Condos/Penthouse', 'Big-D Condos/Penthouse', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (14, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (34, 14, 'Admin: Update As-builts (Tv locations and any other wiring changes)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (35, 14, 'Install: AV Mech Room - PICTURES OF SERVICE SMURF TUBE PRE-DRYWALL (USE DURING INSTALL)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (36, 14, 'Install: Living Room - find out if we will blind wire the Tv wiring or if we need to put it in a single gang box', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (37, 14, 'Install: Move WAP location in Pantry; center it between door and access panel.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (38, 14, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (39, 14, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (40, 14, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (14, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (14, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (14, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (14, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (15, 'WPR Condo 201', 'WPR', 'Condos/Penthouse', 'Big-D Condos/Penthouse', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (15, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (41, 15, 'Admin: Item needs to be added/requested in WeQuote for the job: (1ea) Future Automation IWRE4. Note taken by Quincy on 1/21/26', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (42, 15, 'Install: Coordinate with Helix to run power lines to the shade panel.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (43, 15, 'Install: AV Mech Room - PICTURES OF SERVICE SMURF TUBE PRE-DRYWALL (USE DURING INSTALL)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (44, 15, 'Install: Living Room - Sub location needs power (either move sub or get them to move power)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (45, 15, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (46, 15, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (47, 15, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (222, 15, 'Procore #1794: Unit #201 primary suite/ flex wall has a keypad that is not called out on plans', 'done', 'procore', 'https://app.procore.com/webclients/host/companies/9207/projects/2884198/tools/observations/quality/details/22131860');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (223, 15, 'This is a test to see how a task looks adding it manually.', 'done', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (224, 15, 'Procore #1791: Unit #201 data wires hanging out of wall in family room.', 'done', 'procore', 'https://app.procore.com/webclients/host/companies/9207/projects/2884198/tools/observations/quality/details/22131827');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (15, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (15, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (15, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (15, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (16, 'WPR Condo 202', 'WPR', 'Condos/Penthouse', 'Big-D Condos/Penthouse', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (16, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (48, 16, 'Admin: Item needs to be added/requested in WeQuote for the job: (1ea) Future Automation IWRE4. Note taken by Quincy on 1/21/26', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (49, 16, 'Install: AV Mech Room - PICTURES OF SERVICE SMURF TUBE PRE-DRYWALL (USE DURING INSTALL)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (50, 16, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (51, 16, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (52, 16, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (226, 16, 'Procore #1540: Unit 202 elevator vestibule the keypad is to high.', 'todo', 'procore', 'https://app.procore.com/webclients/host/companies/9207/projects/2884198/tools/observations/quality/details/21457273');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (227, 16, 'Procore #1471: Unit #202 elevator closet the data port is not centered per RCP', 'todo', 'procore', 'https://app.procore.com/webclients/host/companies/9207/projects/2884198/tools/observations/quality/details/21298125');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (16, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (16, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (16, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (16, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (17, 'WPR Condo Penthouse', 'WPR', 'Condos/Penthouse', 'Big-D Condos/Penthouse', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (17, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (9, 17, 'Admin: Item needs to be added/requested in WeQuote for the job: (1ea) Future Automation IWRE4. Note taken by Quincy on 1/21/26', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (10, 17, 'Admin: Primary Bath Small Ap Speakers - 3" round retro (bezel)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (11, 17, 'Admin: Current Proposal - Rec Room shows PS 80 mount... we only have a WB31 in place here. This will need to be a PS65 mount and will require a vesa adapter for the Frame Tv spec''d.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (12, 17, 'Install: Need clarification on keypad in Junior Primary Closet', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (13, 17, 'Install: Discuss with Justin about pulling power lines to the shade panels.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (14, 17, 'Install: Sauna, needs dvc landed in a speaker bracket (sonance medium ring) once ceiling grid is framed', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (15, 17, 'Install: Primary Steam Shower - need to see if we can get a cat6 to the steam shower controller (need to verify with Shamrock/Plummers if this goes to the single gang box inside the steam shower or to a separate controller)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (16, 17, 'Install: Rec Room WB31 - touch base with Jason to see if this box can be mounted yet (it was left tacked to the wall). See if BigD need any more info from us. (Sheet rockers are moving so I don''t want to get caught without this being in place while they put up wall finishes)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (17, 17, 'Install: Talk to Shamrock about network cable in Sauna.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (18, 17, 'Install: AV Mech Room - get a picture of the wall in the mech room where the smurf tube meets the metal conduit that runs to the basement (BEFORE SHEETROCK). Post this on Basecamp in the ATI > Plans folder.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (19, 17, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (20, 17, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (21, 17, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (225, 17, 'Procore #1645: Unit #300 primary suite data port is at 5’ AFF', 'todo', 'procore', 'https://app.procore.com/webclients/host/companies/9207/projects/2884198/tools/observations/quality/details/21714075');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (248, 17, 'Procore #2299: Wire for roller shade needs to be buried in drywall', 'todo', 'procore', 'https://app.procore.com/webclients/host/companies/9207/projects/2884198/tools/observations/quality/details/22970669');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (17, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (17, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (17, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (17, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (18, 'Skier Services', 'WPR', 'Skier Services', 'Big-D Skier Services', 0, '2025-06-04', '2026-11-30');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (18, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (53, 18, 'Admin: Network Switch ? - is Sigil providing us a network switch for the AV rack?', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (54, 18, 'Admin: (2) WB21 back boxes have been pulled from stock for the LL Fitness area. (1) WB31 pulled from stock for ML Member Lounge. These are on a pending C/O. Need to request ordering once approved and note that these have already been pulled.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (55, 18, 'Admin: Use RCP for Speaker Grills (Round or Square) - we will need to order accordingly (possible C/O)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (56, 18, 'Admin: AV Mech - NEED CHANGE ORDER - switch AV Rack to match the rack being provided for the IT rack. Model information is in the notes (also add cage nut replacement ... RACK STUDS)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (57, 18, 'Admin: Wade, where are we at with the change order for the volume controls and touch panels? Do we have time to edit that C/O for a few more changes that are happening. (Square vs round speaker grills in certain areas... and the AV rack needs to change to the same model that Sigil is providing for the network/IT.)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (58, 18, 'Admin: Possible C/O - need to check speaker count on RCP compared to our contract.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (59, 18, 'Install: Install TV Box in Main Lounge and land wires.', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (60, 18, 'Install: ML Members Lounge - WB31 TV back box height - Center of WB box at 66" above finished floor. (Per Eric at WPR)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (61, 18, 'Install: Final Room Checklist has been completed.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (62, 18, 'Install: Project has been verified as complete with Project Manager', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (63, 18, 'Install: Project is ready for Client Training / Service Turnover to be scheduled', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (209, 18, 'Admin: ALIGNED SPEAKERS GRILLS', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (229, 18, 'Procore #257: Incomplete Speakers at member lockers', 'todo', 'procore', 'https://app.procore.com/webclients/host/companies/9207/projects/3124477/tools/observations/quality/details/22470348');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (234, 18, 'Install: Install 18 Speaker Rings in Member Locker Area and land speaker wires (Main Level)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (235, 18, 'Install: Install 2 Speaker Rings in Corridor and land speaker wires (Main Level)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (236, 18, 'Install: Install 2 Speaker Rings in Day Lockers and land speaker wires (Main Level)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (237, 18, 'Install: Install 4 speaker rings in Men’s and Women’s RR and land speaker wires (Main Level)', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (238, 18, 'Install: Install 2 Speaker Rings in Ski Vallet and land speaker wires (Main Level)', 'done', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (18, 'handover', 'WPR Handover (Big-D → WPR)', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (18, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (18, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (18, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (19, 'Metni', 'Other Projects', '', '', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (19, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (154, 19, 'Warehouse: Please stage the bin for this job.', 'done', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (155, 19, 'AV: Admin: Starlink location - steal SH Cat6 from Loft RTV. We can find the wire where it runs through the mech room up in the loft and punch through to the exterior (location needs to be verified with MCC)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (156, 19, 'AV: Admin: Update Solar System Network drawings', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (157, 19, 'AV: Admin: Garage: Make sure that the two network switches are setup and documented properly', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (158, 19, 'AV: Admin: Relabel Equipment accordingly. (See Notes)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (159, 19, 'AV: Admin: Check Wifi is disabled on Hardwired Sonos devices - unless wireless needed to a sub.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (160, 19, 'AV: Punch List: ML/LL: ML Deck WAP was relocated to the Lap Pool. Need to update the name of this WAP in Ubiquiti', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (161, 19, 'AV: Punch List: ML: Deck- Add new WAP to Ubiquiti system', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (162, 19, 'AV: Techs Priority List: Label Master Bathroom Mirror tv spares', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (163, 19, 'AV: Techs Priority List: Master landscape speaker pair needs a box, box will be buried in the dirt because wire comes out below grade, speaker 243 here needs deleted from as built as it was taken to make the master ceiling speaker work, only 1 wire here is good', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (164, 19, 'AV: Techs Priority List: Need to set static IP on garage solar switch, adopt spa outdoor AP and DHCP Res for ski bridge PTZ', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (165, 19, 'AV: Techs Priority List: Transfer Sonos to customer account or default Ports and Amps if no account created by end of install.', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (166, 19, 'AV: UL - Loft: Install Starlink on roof as designated by builder', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (167, 19, 'AV: UL - Loft: Install Starlink modem in mech room', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (168, 19, 'AV: ML - Fire: Remove WAP antennas and paint black', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (169, 19, 'AV: ML - Fire: Install PTZ camera with recess kit', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (170, 19, 'AV: ML - Fire: Install owner provided TV', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (171, 19, 'AV: ML - Office: Deck: remove WAP antennas and paint black', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (172, 19, 'AV: ML - Sunken Hearth RM: Speaker Bar Sonos amp to be installed behind the TV', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (173, 19, 'AV: ML - Master Suite: Change Lap Pool Sonos Port to Master Bedroom in Sonos app', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (174, 19, 'AV: ML - Master Suite: Relable wiring on Sonos Port that used to be Lap Pool which is now Master Bed - audio cable and network', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (175, 19, 'AV: ML - Master Suite: Install owner provided TV w/ soundbar', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (176, 19, 'AV: ML - Outdoor Living: Remove WAP antennas and paint black', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (177, 19, 'AV: ML - Outdoor Living: Install owner provided TV', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (178, 19, 'AV: ML - Garage: Label solar system network wiring', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (179, 19, 'AV: ML - Garage: Garage Exterior: clean off camera', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (180, 19, 'AV: ML - Garage: Mudroom Entry: reinstall camera', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (181, 19, 'AV: ML - Garage: Security switch on 2nd door to the right: see if it can be fished down and brought through lower plate', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (182, 19, 'AV: ML - Garage: Third and fourth door to the right: install passthrough plate', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (183, 19, 'AV: ML - Garage: Battery Bunker: Check on network switch', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (184, 19, 'AV: LL - Batcave: Install X2 cameras (this is based on a pending change order)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (185, 19, 'AV: LL - Lap Pool: Install fisheye camera w/ recessed kit', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (186, 19, 'AV: LL - Theater: Add projector lens presets to Crestron', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (187, 19, 'AV: LL - Theater: Verify that the projector is online and test for functionality', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (188, 19, 'AV: LL - Theater: Straighten projector with screen (it''s twisted to the left)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (189, 19, 'AV: LL - Theater: Place wire wrap around wires going to projector', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (190, 19, 'AV: LL - Theater: Remove plastic from projector', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (191, 19, 'AV: LL - Yoga Area: Install owner provided TV (after mirror is installed)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (192, 19, 'AV: LL - Outdoor Living: Remove WAP antennas and paint black', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (193, 19, 'AV: LL - Outdoor Living: Install owner provided TV', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (194, 19, 'AV: BL Lounge: Install speaker grills x4', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (195, 19, 'AV: BL - Gun Display: Install WAP', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (196, 19, 'AV: BL - Gun Display: Install camera', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (197, 19, 'AV: BL - Gun Display: Install 10U rack w/ all related equipment', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (198, 19, 'AV: BL - Safe Room: Install camera (new camera pending on change order)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (199, 19, 'AV: BL - Main Mech: Elevator Panel phone connection', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (200, 19, 'AV: BL - Main Mech: Clean up wiring', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (201, 19, 'AV: BL - Main Mech: Lutron Processor Panel: Verify blue Cat6 3PC wire for network connection. Update 2-Post I/O sheet', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (202, 19, 'AV: BL - Staff Entry: Exterior Entrance: Install metal box or wood backing for camera', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (203, 19, 'AV: BL - Staff Entry: Install camera (pending rock work)', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (204, 19, 'AV: BL - Rack Room: Move speaker wiring in rack for Lap Pool to distribution amp for Pool speakers', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (205, 19, 'AV: BL - Rack Room: Get a latch for the side of the 2-post', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (206, 19, 'AV: BL - Pool Mech: Install blank plate on wall', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (207, 19, 'AV: BL - Bowling Alley: Verify network connectivity for bowling alley equipment', 'todo', 'pulse', '');
INSERT INTO tasks (id, project_id, name, status, source, external_url) VALUES (208, 19, 'AV: BL - Bowling Alley: Push RTV wiring into wall and place a white blank plate on top', 'todo', 'pulse', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (19, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (19, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (19, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (20, 'D35', 'Other Projects', '', '', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (20, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (20, 'prewire', 'Pre-Wire', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (20, 'trim', 'Trim', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (20, 'install', 'Install', '', '', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (21, 'D4', 'Other Projects', '', '', 0, '2026-02-02', '2026-12-28');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (21, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (21, 'prewire', 'Pre-Wire', '2026-04-13', '2026-07-13', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (21, 'trim', 'Trim', '2026-11-09', '2026-11-16', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (21, 'install', 'Install', '2026-11-30', '2026-12-14', '');
INSERT INTO projects (id, name, project_group, segment, external_team, percent, starts_at, ends_at) VALUES (22, 'Parkin', 'Other Projects', '', 'Jennifer Parkin', 0, '', '');
INSERT INTO project_controls (project_id, next_outcome, next_move_owner, operating_state, blocked, blocker_reason, delay_consequence, next_action, response_date, review_date, escalation_date, last_movement_date, evidence, control_notes, escalation_level, last_escalation_action, event_trigger, override_daily, contract_status, deposit_status, change_order_status, updated_at) VALUES (22, '', '', 'Stable', 0, '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (22, 'prewire', 'Pre-Wire', '', '', 'complete');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (22, 'trim', 'Trim', '', '', 'complete');
INSERT INTO timelines (project_id, key, label, start, end, status) VALUES (22, 'install', 'Install', '', '', '');
